---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: vcloud-csi-registrar
  labels:
    app.kubernetes.io/name: vcloud-csi-driver
    app.kubernetes.io/component: node

roleRef:
  kind: ClusterRole
  name: vcloud-csi-registrar
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: vcloud-csi-node

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: vcloud-csi-provisioner
  labels:
    app.kubernetes.io/name: vcloud-csi-driver
    app.kubernetes.io/component: driver

roleRef:
  kind: ClusterRole
  name: vcloud-csi-provisioner
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: vcloud-csi-driver

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: vcloud-csi-attacher
  labels:
    app.kubernetes.io/name: vcloud-csi-driver
    app.kubernetes.io/component: driver

roleRef:
  kind: ClusterRole
  name: vcloud-csi-attacher
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: vcloud-csi-driver

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: vcloud-csi-resizer
  labels:
    app.kubernetes.io/name: vcloud-csi-driver
    app.kubernetes.io/component: driver

roleRef:
  kind: ClusterRole
  name: vcloud-csi-resizer
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: vcloud-csi-driver

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: vcloud-csi-snapshotter
  labels:
    app.kubernetes.io/name: vcloud-csi-driver
    app.kubernetes.io/component: driver

roleRef:
  kind: ClusterRole
  name: vcloud-csi-snapshotter
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: vcloud-csi-driver
