---
apiVersion: storage.k8s.io/v1
kind: CSIDriver

metadata:
  name: vcloud.csi.proact.de
  labels:
    app.kubernetes.io/name: vcloud-csi-driver

spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
