apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

commonLabels:
  app.kubernetes.io/version: 1.0.0-alpha1

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml

  - csidriver.yml
  - storageclass.yml

  - service.yml
  - deployment.yml
  - daemonset.yml

secretGenerator:
- name: vcloud-csi-driver
  literals:
    - href=https://vcloud.example.com/api
    - insecure=false
    - username=username
    - password=p455w0rd
    - org=my-org
    - vdc=my-vdc

images:
  - name: vcloud-driver
    newName: docker.io/proactcloud/vcloud-csi-driver
    newTag: "latest"

  - name: csi-provisioner
    newName: k8s.gcr.io/sig-storage/csi-provisioner
    newTag: "v2.1.2"
  - name: csi-attacher
    newName: k8s.gcr.io/sig-storage/csi-attacher
    newTag: "v3.2.0"
  - name: csi-resizer
    newName: k8s.gcr.io/sig-storage/csi-resizer
    newTag: "v1.1.0"
  - name: csi-snapshotter
    newName: k8s.gcr.io/sig-storage/csi-snapshotter
    newTag: "v4.0.0"

  - name: node-registrar
    newName: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    newTag: "v2.1.0"

  - name: liveness-probe
    newName: k8s.gcr.io/sig-storage/livenessprobe
    newTag: "v2.2.0"
