---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: vcloud-csi-node
  labels:
    app.kubernetes.io/name: vcloud-csi-driver
    app.kubernetes.io/component: node

---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: vcloud-csi-driver
  labels:
    app.kubernetes.io/name: vcloud-csi-driver
    app.kubernetes.io/component: driver
