---
apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: vcloud
  labels:
    app.kubernetes.io/name: vcloud-csi-driver
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"

provisioner: vcloud.csi.proact.de
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate

parameters:
  storageProfile: default
