name: docs

on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v2

      - name: Setup hugo
        id: hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'

      - name: Build pages
        id: build
        run: make docs

      - name: Deploy pages
        id: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: docs/public/
