name: docs

on:
  push:
    branches:
      - master
    paths:
      - docs/

jobs:
  changes:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

      - name: Setup hugo
        id: hugo
        uses: peaceiris/actions-hugo@c03b5dbed22245418539b65eb9a3b1d5fdd9a0a6 # renovate: tag=v2
        with:
          hugo-version: '0.80.0'

      - name: Build pages
        id: build
        run: make docs

      - name: Deploy pages
        id: publish
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: docs/public/
