name: release

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2

      - name: Setup golang
        id: golang
        uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57 # renovate: tag=v2
        with:
          go-version: 1.15

      - name: Run generate
        id: generate
        run: make generate

      - name: Run build
        id: build
        run: make build

      - name: Image metadata
        id: meta
        uses: crazy-max/ghaction-docker-meta@9be43f076db7f0f4ac30d81183fc9d956b9e9eb6 # renovate: tag=v1
        with:
          images: proactcloud/vcloud-csi-driver
          tag-latest: true
          tag-semver: |
            {{ version }}
            {{ major }}.{{ minor }}
          label-custom: |
            maintainer=Proact Deutschland GmbH <devops@proactcloud.de>
            org.opencontainers.image.title=vcloud-csi-driver
            org.opencontainers.image.description=A Container Storage Interface (CSI) Driver for VMWare vCloud Director
            org.opencontainers.image.vendor=Proact Deutschland GmbH

      - name: Setup qemu
        id: qemu
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # renovate: tag=v1

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1

      - name: Docker login
        id: login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # renovate: tag=v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        id: publish
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2
        with:
          context: .
          file: cmd/vcloud-csi-driver/Dockerfile
          platforms: linux/amd64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
